"""empty message

Revision ID: 26df2fdcc4b8
Revises: a402d5166a7e
Create Date: 2021-04-13 15:12:15.417200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26df2fdcc4b8'
down_revision = 'a402d5166a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('seeking_description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
